--
create table FX_SYSLOG
(
  USERID    VARCHAR2(50),
  TYPEKEY   VARCHAR2(50),
  ACTION    VARCHAR2(50),
  LOGDATE   DATE,
  LOGRESULT CLOB
)
-- Create table
create table FX_USERPRIVILEGER
(
  USERID   VARCHAR2(50),
  PID      VARCHAR2(50),
  ORIGIN   VARCHAR2(50),
  ORIGINID VARCHAR2(50)
)
alter table FX_USERINFO
    add PORTAlCONFIG clob
alter table FX_Privilege 
    add ModelKey VARCHAR2(50)
 --Î´Íê
ALTER TABLE FX_WORKFLOWCASE ADD ENDER VARCHAR2(50)
ALTER TABLE FX_WORKFLOWCASE ADD ENDERCNNAME VARCHAR2(50)
ALTER TABLE FX_WORKFLOWCASE ADD ENDDATE DATE

--
ALTER TABLE FX_USERINFO ADD RANKID VARCHAR(50)
ALTER TABLE FX_DEPARTMENT ADD RANKID VARCHAR(50)


create table FX_AttachMent
(
  AutoID VARCHAR2(200) ,
  CaseID VARCHAR2(200) ,
  ActID VARCHAR2(200),
  ActName VARCHAR2(200),
  FileName VARCHAR2(200),
  FilePath VARCHAR2(200),
  UploadDate VARCHAR2(200),
  UserID VARCHAR2(200) 
)

